import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import type { LessonStatus, ReviewQuestion, Tag, Understanding } from "./types.js";

export const lessons = sqliteTable("lessons", {
  id: text("id").primaryKey(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  tool: text("tool").notNull(),
  projectPath: text("project_path").notNull(),
  title: text("title").notNull(),
  originalPrompt: text("original_prompt").notNull(),
  problem: text("problem").notNull(),
  mistake: text("mistake").notNull(),
  rootCause: text("root_cause").notNull(),
  fixSummary: text("fix_summary").notNull(),
  takeaway: text("takeaway"),
  mistakePattern: text("mistake_pattern"),
  concepts: text("concepts", { mode: "json" }).$type<string[]>().notNull(),
  filesChanged: text("files_changed", { mode: "json" }).$type<string[]>().notNull(),
  codeExample: text("code_example"),
  badCodeExample: text("bad_code_example"),
  goodCodeExample: text("good_code_example"),
  codeExplanation: text("code_explanation"),
  practiceTask: text("practice_task"),
  reviewQuestions: text("review_questions", { mode: "json" }).$type<ReviewQuestion[]>().notNull(),
  understanding: text("understanding").$type<Understanding>().notNull(),
  nextReviewAt: text("next_review_at").notNull(),
  reviewCount: integer("review_count").notNull().default(0),
  sourceDiff: text("source_diff"),
  tags: text("tags", { mode: "json" }).$type<Tag[]>().notNull(),
  status: text("status").$type<LessonStatus>().notNull().default("active"),
  supersededBy: text("superseded_by"),
  supersedes: text("supersedes"),
  supersedeReason: text("supersede_reason"),
});
